### ISSUE TITLE
Bounding boxes display incorrectly

### ISSUE THREAD

**Issue by arjunkeerthi** [csvance/keras-mobile-detectnet#3]
Hi, thanks for this project. I'm running the inference script with 
`python inference.py --inference-type FP16 --test-path (path to folder containing images)`
but the bounding boxes displayed do not correlate to the image itself. For examples, here are the outputs for three sample images:

![image](https://user-images.githubusercontent.com/32022213/62070588-6e319c80-b200-11e9-8d74-3ca23f6bddfe.png)

![image](https://user-images.githubusercontent.com/32022213/62070648-87d2e400-b200-11e9-86f2-a4c15bd1c5eb.png)

![image](https://user-images.githubusercontent.com/32022213/62070704-a638df80-b200-11e9-959d-29134566fc03.png)

The first one is particularly worrying since only one object should be detected, but numerous boxes are still being displayed.

Thanks

**Comment by csvance** [comment]
Hi, did you train the model with images of cars and use the ?weights parameter to use your trained network weights file? The network includes weights trained for detecting squirrels (weights/squirrel_detector.hdf5)On Mon, Jul 29, 2019 at 1:00 PM arjunkeerthi <notifications@github.com> wrote:Hi, thanks for this project. I'm running the inference script with
python inference.py --inference-type FP16 --test-path (path to folder containing images)
but the bounding boxes displayed do not correlate to the image itself. For examples, here are the outputs for three sample images:



The first one is particularly worrying since only one object should be detected, but numerous boxes are still being displayed.
Thanks

?You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by arjunkeerthi** [comment]
Wow, I completely missed that. Thanks for the reply!
